"""add crud os module

Revision ID: 333542ef649c
Revises: acd301a93cf4
Create Date: 2025-11-17 11:02:09.587331

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "333542ef649c"
down_revision = "acd301a93cf4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badge",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("base_xp", sa.Integer(), server_default="50", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("badge_pkey")),
        sa.UniqueConstraint("slug", name=op.f("badge_slug_key")),
    )
    op.create_table(
        "track",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("track_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("track_pkey")),
    )
    op.create_index("idx_track_user", "track", ["user_id"], unique=False)
    op.create_table(
        "user_badge",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("badge_id", sa.UUID(), nullable=False),
        sa.Column(
            "awarded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["badge_id"],
            ["badge.id"],
            name=op.f("user_badge_badge_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("user_badge_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "badge_id", name=op.f("user_badge_pkey")),
    )
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("xp_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "current_streak_days", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("last_active_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("user_stats_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_stats_pkey")),
    )
    op.create_table(
        "node",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("TASK", "HABIT", "FOCUS_SESSION", "MILESTONE", name="node_type"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_xp", sa.Integer(), server_default="10", nullable=False),
        sa.Column("is_locked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
            name=op.f("node_track_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("node_pkey")),
    )
    op.create_index("idx_node_track", "node", ["track_id"], unique=False)
    op.create_index("idx_node_type", "node", ["type"], unique=False)
    op.create_table(
        "doc",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("track_id", sa.UUID(), nullable=True),
        sa.Column("node_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"], ["node.id"], name=op.f("doc_node_id_fkey"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
            name=op.f("doc_track_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("doc_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("doc_pkey")),
    )
    op.create_index("idx_doc_node", "doc", ["node_id"], unique=False)
    op.create_index("idx_doc_track", "doc", ["track_id"], unique=False)
    op.create_index("idx_doc_user", "doc", ["user_id"], unique=False)
    op.create_table(
        "habit_schedule",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum("DAILY", "WEEKLY", "MONTHLY", name="habit_frequency"),
            nullable=False,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
            name=op.f("habit_schedule_node_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("node_id", name=op.f("habit_schedule_pkey")),
    )
    op.create_table(
        "node_completion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("MANUAL", "SESSION", name="completion_source"),
            nullable=False,
        ),
        sa.Column("earned_xp", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
            name=op.f("node_completion_node_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("node_completion_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("node_completion_pkey")),
    )
    op.create_index("idx_completion_node", "node_completion", ["node_id"], unique=False)
    op.create_index("idx_completion_user", "node_completion", ["user_id"], unique=False)
    op.create_table(
        "time_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "duration_min",
            sa.Integer(),
            sa.Computed(
                "(EXTRACT(EPOCH FROM (ended_at - started_at)) / 60)::int",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
            name=op.f("time_entry_node_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("time_entry_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("time_entry_pkey")),
    )
    # Create immutable function for date extraction
    op.execute("""
        CREATE OR REPLACE FUNCTION immutable_date(timestamp with time zone)
        RETURNS date
        LANGUAGE sql
        IMMUTABLE
        AS $$
            SELECT $1::date;
        $$;
    """)
    op.create_index(
        "idx_time_entry_date",
        "time_entry",
        [sa.text("immutable_date(started_at)")],
        unique=False,
    )
    op.create_index("idx_time_entry_node", "time_entry", ["node_id"], unique=False)
    op.create_index("idx_time_entry_user", "time_entry", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_time_entry_user", table_name="time_entry")
    op.drop_index("idx_time_entry_node", table_name="time_entry")
    op.drop_index("idx_time_entry_date", table_name="time_entry")
    # Drop the immutable function
    op.execute("DROP FUNCTION IF EXISTS immutable_date(timestamp with time zone)")
    op.drop_table("time_entry")
    op.drop_index("idx_completion_user", table_name="node_completion")
    op.drop_index("idx_completion_node", table_name="node_completion")
    op.drop_table("node_completion")
    op.drop_table("habit_schedule")
    op.drop_index("idx_doc_user", table_name="doc")
    op.drop_index("idx_doc_track", table_name="doc")
    op.drop_index("idx_doc_node", table_name="doc")
    op.drop_table("doc")
    op.drop_index("idx_node_type", table_name="node")
    op.drop_index("idx_node_track", table_name="node")
    op.drop_table("node")
    op.drop_table("user_stats")
    op.drop_table("user_badge")
    op.drop_index("idx_track_user", table_name="track")
    op.drop_table("track")
    op.drop_table("badge")
    # ### end Alembic commands ###
