"""delete game world feature

Revision ID: acd301a93cf4
Revises: 561948a1bb69
Create Date: 2025-11-17 10:16:52.378382

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "acd301a93cf4"
down_revision = "561948a1bb69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("focus_session_user_id_idx", table_name="focus_session")
    op.drop_table("focus_session")
    op.drop_table("hero_profile")
    op.drop_index("inventory_item_user_id_idx", table_name="inventory_item")
    op.drop_table("inventory_item")
    op.drop_table("world_state")
    op.drop_table("cosmetic_item")
    op.drop_index("task_template_user_id_idx", table_name="task_template")
    op.drop_table("task_template")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_template",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
        sa.Column(
            "default_duration", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "room",
            postgresql.ENUM("STUDY", "BUILD", "TRAINING", name="room_name"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "default_duration > 0", name="task_template_duration_positive_check_check"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="task_template_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="task_template_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "task_template_user_id_idx", "task_template", ["user_id"], unique=False
    )
    op.create_table(
        "cosmetic_item",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column(
            "slot",
            postgresql.ENUM("HAT", "OUTFIT", "ACCESSORY", name="cosmetic_slot"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "rarity",
            postgresql.ENUM("COMMON", "RARE", "EPIC", name="cosmetic_rarity"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sprite_key", sa.VARCHAR(length=120), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="cosmetic_item_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "world_state",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "study_room_level", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "build_room_level", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "training_room_level", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("plaza_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "total_sessions_success", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("day_streak", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("longest_streak", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("last_session_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="world_state_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="world_state_pkey"),
        sa.UniqueConstraint("user_id", name="world_state_user_id_key"),
    )
    op.create_table(
        "inventory_item",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("item_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["cosmetic_item.id"],
            name="inventory_item_item_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="inventory_item_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="inventory_item_pkey"),
        sa.UniqueConstraint("user_id", "item_id", name="inventory_item_user_item_key"),
    )
    op.create_index(
        "inventory_item_user_id_idx", "inventory_item", ["user_id"], unique=False
    )
    op.create_table(
        "hero_profile",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("exp", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("gold", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("equipped_hat_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("equipped_outfit_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "equipped_accessory_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["equipped_accessory_id"],
            ["cosmetic_item.id"],
            name="hero_profile_equipped_accessory_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["equipped_hat_id"],
            ["cosmetic_item.id"],
            name="hero_profile_equipped_hat_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["equipped_outfit_id"],
            ["cosmetic_item.id"],
            name="hero_profile_equipped_outfit_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="hero_profile_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="hero_profile_pkey"),
        sa.UniqueConstraint("user_id", name="hero_profile_user_id_key"),
    )
    op.create_table(
        "focus_session",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("task_template_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "room",
            postgresql.ENUM("STUDY", "BUILD", "TRAINING", name="session_room"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "duration_minutes", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expected_end_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cancelled_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "SUCCESS", "CANCELLED", name="session_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reward_exp", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("reward_gold", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "reward_cosmetic_item_id", sa.UUID(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "duration_minutes > 0", name="focus_session_session_duration_positive_check"
        ),
        sa.ForeignKeyConstraint(
            ["reward_cosmetic_item_id"],
            ["cosmetic_item.id"],
            name="focus_session_reward_cosmetic_item_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_template_id"],
            ["task_template.id"],
            name="focus_session_task_template_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="focus_session_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="focus_session_pkey"),
    )
    op.create_index(
        "focus_session_user_id_idx", "focus_session", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
