"""lifeos phase 1 tables

Revision ID: 561948a1bb69
Revises:
Create Date: 2025-11-16 16:34:47.183198

"""

from uuid import uuid4

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "561948a1bb69"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cosmetic_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "slot",
            sa.Enum("HAT", "OUTFIT", "ACCESSORY", name="cosmetic_slot"),
            nullable=False,
        ),
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "RARE", "EPIC", name="cosmetic_rarity"),
            nullable=False,
        ),
        sa.Column("sprite_key", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cosmetic_item_pkey")),
    )
    cosmetic_items_table = sa.table(
        "cosmetic_item",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String(length=120)),
        sa.column(
            "slot",
            sa.Enum("HAT", "OUTFIT", "ACCESSORY", name="cosmetic_slot"),
        ),
        sa.column(
            "rarity",
            sa.Enum("COMMON", "RARE", "EPIC", name="cosmetic_rarity"),
        ),
        sa.column("sprite_key", sa.String(length=120)),
        sa.column("description", sa.Text()),
    )
    op.bulk_insert(
        cosmetic_items_table,
        [
            {
                "id": uuid4(),
                "name": "Aurora Headband",
                "slot": "HAT",
                "rarity": "COMMON",
                "sprite_key": "hat-aurora",
                "description": "Soft gradient band that glows after focus sessions.",
            },
            {
                "id": uuid4(),
                "name": "Circuit Crown",
                "slot": "HAT",
                "rarity": "RARE",
                "sprite_key": "hat-circuit",
                "description": "Shimmering halo made of holo-circuit traces.",
            },
            {
                "id": uuid4(),
                "name": "Builder Hoodie",
                "slot": "OUTFIT",
                "rarity": "COMMON",
                "sprite_key": "outfit-builder",
                "description": "Cozy hoodie earned from consistent build sessions.",
            },
            {
                "id": uuid4(),
                "name": "Nebula Cloak",
                "slot": "OUTFIT",
                "rarity": "EPIC",
                "sprite_key": "outfit-nebula",
                "description": "Flowing cloak that trails constellations.",
            },
            {
                "id": uuid4(),
                "name": "Focus Band",
                "slot": "ACCESSORY",
                "rarity": "COMMON",
                "sprite_key": "accessory-focus-band",
                "description": "Minimal band symbolizing daily dedication.",
            },
            {
                "id": uuid4(),
                "name": "Quantum Visor",
                "slot": "ACCESSORY",
                "rarity": "RARE",
                "sprite_key": "accessory-quantum-visor",
                "description": "Translucent visor that reacts to streak milestones.",
            },
        ],
    )
    op.create_table(
        "user",
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("profile_picture", sa.Text(), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("user_email_idx"), "user", ["email"], unique=True)
    op.create_table(
        "hero_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("exp", sa.Integer(), nullable=False),
        sa.Column("gold", sa.Integer(), nullable=False),
        sa.Column("equipped_hat_id", sa.UUID(), nullable=True),
        sa.Column("equipped_outfit_id", sa.UUID(), nullable=True),
        sa.Column("equipped_accessory_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["equipped_accessory_id"],
            ["cosmetic_item.id"],
            name=op.f("hero_profile_equipped_accessory_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["equipped_hat_id"],
            ["cosmetic_item.id"],
            name=op.f("hero_profile_equipped_hat_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["equipped_outfit_id"],
            ["cosmetic_item.id"],
            name=op.f("hero_profile_equipped_outfit_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("hero_profile_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("hero_profile_pkey")),
        sa.UniqueConstraint("user_id", name=op.f("hero_profile_user_id_key")),
    )
    op.create_table(
        "inventory_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["cosmetic_item.id"],
            name=op.f("inventory_item_item_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("inventory_item_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("inventory_item_pkey")),
        sa.UniqueConstraint("user_id", "item_id", name="inventory_item_user_item_key"),
    )
    op.create_index(
        op.f("inventory_item_user_id_idx"), "inventory_item", ["user_id"], unique=False
    )
    op.create_table(
        "refresh_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_from_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rotated_from_id"],
            ["refresh_session.id"],
            name=op.f("refresh_session_rotated_from_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("refresh_session_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("refresh_session_pkey")),
    )
    op.create_index(
        "ix_refresh_active", "refresh_session", ["user_id", "expires_at"], unique=False
    )
    op.create_index(
        op.f("refresh_session_token_hash_idx"),
        "refresh_session",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("refresh_session_user_id_idx"),
        "refresh_session",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "task_template",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("default_duration", sa.Integer(), nullable=False),
        sa.Column(
            "room",
            sa.Enum("STUDY", "BUILD", "TRAINING", name="room_name"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "default_duration > 0",
            name=op.f("task_template_duration_positive_check_check"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("task_template_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_template_pkey")),
    )
    op.create_index(
        op.f("task_template_user_id_idx"), "task_template", ["user_id"], unique=False
    )
    op.create_table(
        "world_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("study_room_level", sa.Integer(), nullable=False),
        sa.Column("build_room_level", sa.Integer(), nullable=False),
        sa.Column("training_room_level", sa.Integer(), nullable=False),
        sa.Column("plaza_level", sa.Integer(), nullable=False),
        sa.Column("total_sessions_success", sa.Integer(), nullable=False),
        sa.Column("day_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_session_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("world_state_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("world_state_pkey")),
        sa.UniqueConstraint("user_id", name=op.f("world_state_user_id_key")),
    )
    op.create_table(
        "focus_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("task_template_id", sa.UUID(), nullable=True),
        sa.Column(
            "room",
            sa.Enum("STUDY", "BUILD", "TRAINING", name="session_room"),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("expected_end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "CANCELLED", name="session_status"),
            nullable=False,
        ),
        sa.Column("reward_exp", sa.Integer(), nullable=True),
        sa.Column("reward_gold", sa.Integer(), nullable=True),
        sa.Column("reward_cosmetic_item_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "duration_minutes > 0",
            name=op.f("focus_session_session_duration_positive_check"),
        ),
        sa.ForeignKeyConstraint(
            ["reward_cosmetic_item_id"],
            ["cosmetic_item.id"],
            name=op.f("focus_session_reward_cosmetic_item_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_template_id"],
            ["task_template.id"],
            name=op.f("focus_session_task_template_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("focus_session_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("focus_session_pkey")),
    )
    op.create_index(
        op.f("focus_session_user_id_idx"), "focus_session", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("focus_session_user_id_idx"), table_name="focus_session")
    op.drop_table("focus_session")
    op.drop_table("world_state")
    op.drop_index(op.f("task_template_user_id_idx"), table_name="task_template")
    op.drop_table("task_template")
    op.drop_index(op.f("refresh_session_user_id_idx"), table_name="refresh_session")
    op.drop_index(op.f("refresh_session_token_hash_idx"), table_name="refresh_session")
    op.drop_index("ix_refresh_active", table_name="refresh_session")
    op.drop_table("refresh_session")
    op.drop_index(op.f("inventory_item_user_id_idx"), table_name="inventory_item")
    op.drop_table("inventory_item")
    op.drop_table("hero_profile")
    op.drop_index(op.f("user_email_idx"), table_name="user")
    op.drop_table("user")
    op.drop_table("cosmetic_item")
    bind = op.get_bind()
    sa.Enum(name="session_status").drop(bind, checkfirst=True)
    sa.Enum(name="session_room").drop(bind, checkfirst=True)
    sa.Enum(name="room_name").drop(bind, checkfirst=True)
    sa.Enum(name="cosmetic_rarity").drop(bind, checkfirst=True)
    sa.Enum(name="cosmetic_slot").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
